# Generated by Django 2.0.3 on 2018-08-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_auto_20180814_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot_list',
            options={'verbose_name': 'Slot_List', 'verbose_name_plural': 'Slot_List'},
        ),
    ]
